package com.grandstay.shared.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    INVALID_STATE_TRANSITION,
    VALIDATION_FAILED,
    ROOM_NOT_OPERATIONAL,
    ROOM_NOT_AVAILABLE,
    RATE_PLAN_NOT_AVAILABLE,
    PROMOTION_NOT_AVAILABLE,
    PAYMENT_EXCEEDS_BALANCE,
    REFUND_EXCEEDS_PAYMENT,
    VNPAY_PAYMENT_UNAVAILABLE,
    VNPAY_SIGNATURE_INVALID,
    DATA_CONFLICT,
    CONCURRENT_MODIFICATION,
    USERNAME_TAKEN,
    EMAIL_TAKEN,
    INVALID_CREDENTIALS,
    GOOGLE_AUTH_FAILED,
    GOOGLE_AUTH_UNAVAILABLE,
    ACCOUNT_LOCKED,
    TOKEN_INVALID,
    TOKEN_REUSED,
    RATE_LIMITED
}
