import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Pencil, Plus, RotateCcw, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { api, errorMessage } from '../api/client'
import type { HotelService, Page } from '../api/types'
import { Badge, Button, Card, ConfirmDialog, Empty, Loading, Modal, PageHeader, statusTone } from '../components/ui'
import { useAuth } from '../auth/AuthProvider'

type Form = { code: string; name: string; category: string; description: string; unit: string; unitPrice: number; taxRate: number; currency: string; active: boolean }
const blank: Form = { code: '', name: '', category: 'FOOD_BEVERAGE', description: '', unit: 'lần', unitPrice: 0, taxRate: 8, currency: 'VND', active: true }

export function ServicesPage() {
  const query = useQuery({ queryKey: ['services', 'catalog'], queryFn: () => api.get<Page<HotelService>>('/services', { params: { size: 100, includeInactive: true } }).then(r => r.data.content) })
  const [editing, setEditing] = useState<HotelService | 'new' | null>(null)
  const [deleting, setDeleting] = useState<HotelService | null>(null)
  const client = useQueryClient()
  const { can } = useAuth()
  const refresh = () => client.invalidateQueries({ queryKey: ['services'] })
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/services/${id}`), onSuccess: () => { toast.success('Đã xóa dịch vụ khỏi danh mục.'); setDeleting(null); refresh() }, onError: e => toast.error(errorMessage(e)) })
  const restore = useMutation({ mutationFn: (service: HotelService) => api.put(`/services/${service.id}`, { code: service.code, name: service.name, category: service.category, description: service.description ?? null, unit: service.unit, unitPrice: service.unitPrice, taxRate: service.taxRate, currency: service.currency, active: true }), onSuccess: () => { toast.success('Đã bật lại dịch vụ.'); refresh() }, onError: e => toast.error(errorMessage(e)) })
  if (query.isLoading) return <Loading />
  return <><PageHeader title="Danh mục dịch vụ" description="Quản lý cả dịch vụ đang bán và tạm ngưng; chỉ dịch vụ đang bán mới xuất hiện khi ghi nhận cho khách." action={can('service:write') ? <Button onClick={() => setEditing('new')}><Plus size={17}/>Thêm dịch vụ</Button> : undefined}/><Card><div className="table-shell"><table className="data-table"><thead><tr><th>Mã</th><th>Dịch vụ</th><th>Nhóm</th><th>Đơn giá</th><th>Thuế</th><th>Trạng thái</th><th></th></tr></thead><tbody>{query.data?.map(item => <tr key={item.id} className={item.active ? '' : 'bg-slate-50/70'}><td className="font-bold">{item.code}</td><td>{item.name}<div className="text-xs text-ink-soft">/{item.unit}</div></td><td>{item.category}</td><td>{Number(item.unitPrice).toLocaleString('vi-VN')} {item.currency}</td><td>{item.taxRate}%</td><td><Badge tone={statusTone(item.active ? 'ACTIVE' : 'INACTIVE')}>{item.active ? 'Đang bán' : 'Tạm ngưng'}</Badge></td><td><div className="flex justify-end gap-1">{can('service:write') && <>{!item.active && <button aria-label={`Bật lại ${item.name}`} title="Bật lại dịch vụ" className="rounded-lg p-2 text-emerald-700 hover:bg-emerald-50" disabled={restore.isPending} onClick={() => restore.mutate(item)}><RotateCcw size={17}/></button>}<button aria-label={`Sửa ${item.name}`} className="rounded-lg p-2 hover:bg-slate-100" onClick={() => setEditing(item)}><Pencil size={17}/></button><button aria-label={`Xóa ${item.name}`} className="rounded-lg p-2 text-red-600 hover:bg-red-50" onClick={() => setDeleting(item)}><Trash2 size={17}/></button></>}</div></td></tr>)}</tbody></table>{!query.data?.length && <Empty/>}</div></Card>{editing && <ServiceModal service={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); refresh() }}/>} {deleting && <ConfirmDialog title="Xóa dịch vụ khỏi danh mục?" description={`Dịch vụ “${deleting.name}” sẽ không còn xuất hiện trong danh mục. Dữ liệu đã phát sinh vẫn được giữ nguyên.`} confirmLabel="Xóa dịch vụ" loading={remove.isPending} onCancel={() => setDeleting(null)} onConfirm={() => remove.mutate(deleting.id)}/>}</>
}

function ServiceModal({ service, onClose, onSaved }: { service?: HotelService; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<Form>(service ? { code: service.code, name: service.name, category: service.category, description: service.description ?? '', unit: service.unit, unitPrice: Number(service.unitPrice), taxRate: Number(service.taxRate), currency: service.currency, active: service.active } : blank)
  const mutation = useMutation({ mutationFn: () => service ? api.put(`/services/${service.id}`, form) : api.post('/services', form), onSuccess: () => { toast.success('Đã lưu dịch vụ.'); onSaved() }, onError: e => toast.error(errorMessage(e)) })
  const set = <K extends keyof Form>(key: K, value: Form[K]) => setForm(prev => ({ ...prev, [key]: value }))
  return <Modal title={service ? 'Cập nhật dịch vụ' : 'Thêm dịch vụ'} onClose={onClose}><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Mã dịch vụ</span><input className="field" value={form.code} onChange={e => set('code', e.target.value.toUpperCase())}/></label><label><span className="label">Tên dịch vụ</span><input className="field" value={form.name} onChange={e => set('name', e.target.value)}/></label><label><span className="label">Nhóm</span><input className="field" value={form.category} onChange={e => set('category', e.target.value.toUpperCase())}/></label><label><span className="label">Đơn vị</span><input className="field" value={form.unit} onChange={e => set('unit', e.target.value)}/></label><label><span className="label">Đơn giá</span><input type="number" min={0} className="field" value={form.unitPrice} onChange={e => set('unitPrice', Number(e.target.value))}/></label><label><span className="label">Thuế (%)</span><input type="number" min={0} max={100} className="field" value={form.taxRate} onChange={e => set('taxRate', Number(e.target.value))}/></label><label className="sm:col-span-2"><span className="label">Mô tả</span><textarea className="field" value={form.description} onChange={e => set('description', e.target.value)}/></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.active} onChange={e => set('active', e.target.checked)}/>Đang kinh doanh</label></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Đóng</Button><Button disabled={!form.code || !form.name || !form.category || !form.unit} loading={mutation.isPending} onClick={() => mutation.mutate()}>Lưu dịch vụ</Button></div></Modal>
}
