package com.grandstay.service.api;
import java.math.BigDecimal;import java.util.UUID;import com.grandstay.service.application.ServiceCatalogApplicationService;import com.grandstay.service.application.ServiceCatalogApplicationService.Command;import com.grandstay.shared.dto.EntityDtos.ServiceDto;import io.swagger.v3.oas.annotations.tags.Tag;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springdoc.core.annotations.ParameterObject;import org.springframework.data.domain.*;import org.springframework.data.web.PageableDefault;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/services") @Tag(name="Services") public class ServiceController {private final ServiceCatalogApplicationService service;public ServiceController(ServiceCatalogApplicationService s){service=s;}
 @GetMapping @PreAuthorize("hasAuthority('service:read')") public Page<ServiceDto> list(@RequestParam(defaultValue="false") boolean includeInactive,@ParameterObject @PageableDefault(size=20,sort="name") Pageable p){return service.list(p,includeInactive);}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('service:write')") public ServiceDto create(@Valid @RequestBody ServiceRequest r){return service.create(r.command());}
 @PutMapping("/{id}") @PreAuthorize("hasAuthority('service:write')") public ServiceDto update(@PathVariable UUID id,@Valid @RequestBody ServiceRequest r){return service.update(id,r.command());}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAuthority('service:write')") public void pause(@PathVariable UUID id){service.pause(id);}
 public record ServiceRequest(@NotBlank @Size(max=50) String code,@NotBlank @Size(max=150) String name,@NotBlank @Size(max=50) String category,@Size(max=1000) String description,@NotBlank @Size(max=30) String unit,@NotNull @DecimalMin("0") BigDecimal unitPrice,@NotNull @DecimalMin("0") @DecimalMax("100") BigDecimal taxRate,@NotBlank @Pattern(regexp="[A-Za-z]{3}") String currency,boolean active){Command command(){return new Command(code,name,category,description,unit,unitPrice,taxRate,currency,active);}}
}
