package com.grandstay.room.api;
import java.math.BigDecimal;import java.util.UUID;import com.grandstay.room.application.RoomCatalogApplicationService;import com.grandstay.room.application.RoomCatalogApplicationService.RoomTypeCommand;import com.grandstay.shared.dto.EntityDtos.RoomTypeDto;import io.swagger.v3.oas.annotations.tags.Tag;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springdoc.core.annotations.ParameterObject;import org.springframework.data.domain.*;import org.springframework.data.web.PageableDefault;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/room-types") @Tag(name="Room Types")
public class RoomTypeController {private final RoomCatalogApplicationService service;public RoomTypeController(RoomCatalogApplicationService s){service=s;}
 @GetMapping @PreAuthorize("hasAuthority('room:read')") public Page<RoomTypeDto> list(@ParameterObject @PageableDefault(size=20,sort="name") Pageable p){return service.roomTypes(p);}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('room:write')") public RoomTypeDto create(@Valid @RequestBody RoomTypeRequest r){return service.createType(r.command());}
 @PutMapping("/{id}") @PreAuthorize("hasAuthority('room:write')") public RoomTypeDto update(@PathVariable UUID id,@Valid @RequestBody RoomTypeRequest r){return service.updateType(id,r.command());}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAuthority('room:write')") public void delete(@PathVariable UUID id){service.deleteType(id);}
 public record RoomTypeRequest(@NotBlank @Size(max=30) String code,@NotBlank @Size(max=100) String name,@Size(max=1000) String description,@Min(1) int capacityAdults,@Min(0) int capacityChildren,@DecimalMin("0") BigDecimal baseHourlyRate,@DecimalMin("0") BigDecimal baseDailyRate,@NotNull @DecimalMin("0") BigDecimal baseNightlyRate,@NotBlank @Pattern(regexp="[A-Za-z]{3}") String currency){RoomTypeCommand command(){return new RoomTypeCommand(code,name,description,capacityAdults,capacityChildren,baseHourlyRate,baseDailyRate,baseNightlyRate,currency);}}
}
