package com.grandstay.room.api;
import java.time.Instant;import java.util.*;import com.grandstay.room.application.*;import com.grandstay.room.application.RoomCatalogApplicationService.RoomCommand;import com.grandstay.shared.domain.ModelEnums.RoomOperationalStatus;import com.grandstay.shared.dto.EntityDtos.RoomDto;import io.swagger.v3.oas.annotations.tags.Tag;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springdoc.core.annotations.ParameterObject;import org.springframework.data.domain.*;import org.springframework.data.web.PageableDefault;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/rooms") @Tag(name="Rooms")
public class RoomController {private final RoomCatalogApplicationService service;public RoomController(RoomCatalogApplicationService s){service=s;}
 @GetMapping @PreAuthorize("hasAuthority('room:read')") public Page<RoomDto> list(@ParameterObject @PageableDefault(size=50,sort="roomNumber") Pageable p){return service.rooms(p);}
 @GetMapping("/matrix") @PreAuthorize("hasAuthority('room:read')") public List<RoomMatrixResponse> matrix(@RequestParam(required=false) Instant at,Authentication authentication){boolean canReadBookings=authentication.getAuthorities().stream().anyMatch(authority->authority.getAuthority().equals("booking:read")||authority.getAuthority().equals("ROLE_ADMIN"));return service.matrix(at).stream().map(row->new RoomMatrixResponse(row.getRoomId(),row.getRoomNumber(),row.getFloorId(),row.getFloorName(),row.getFloorNumber(),row.getRoomTypeId(),row.getRoomTypeName(),row.getDisplayStatus(),canReadBookings?row.getBookingId():null)).toList();}
 @GetMapping("/available") @PreAuthorize("hasAuthority('room:read')") public List<RoomDto> available(@RequestParam Instant from,@RequestParam Instant to){return service.availableRooms(from,to);}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('room:write')") public RoomDto create(@Valid @RequestBody RoomRequest r){return service.createRoom(r.command());}
 @PutMapping("/{id}") @PreAuthorize("hasAuthority('room:write')") public RoomDto update(@PathVariable UUID id,@Valid @RequestBody RoomRequest r){return service.updateRoom(id,r.command());}
 @PostMapping("/{id}/complete-cleaning") @PreAuthorize("hasAuthority('room:write')") public RoomDto completeCleaning(@PathVariable UUID id){return service.completeCleaning(id);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAuthority('room:write')") public void delete(@PathVariable UUID id){service.deleteRoom(id);}
 public record RoomMatrixResponse(UUID roomId,String roomNumber,UUID floorId,String floorName,Integer floorNumber,UUID roomTypeId,String roomTypeName,String displayStatus,UUID bookingId){}
 public record RoomRequest(@NotBlank @Size(max=20) String roomNumber,@NotNull UUID floorId,@NotNull UUID roomTypeId,@NotNull RoomOperationalStatus status,@Size(max=1000) String notes){RoomCommand command(){return new RoomCommand(roomNumber,floorId,roomTypeId,status,notes);}}
}
